### teste de buscar todos os album
GET http://localhost:40000/getAllAlbum HTTP/1.1
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjk5NDQ4NzM0LCJleHAiOjE2OTk0NDkzMzR9.WOT4pv8ejaGYL1osdPPfaJ4NbimwgNlrB56yWprZsj0

{    
    
}

### teste de buscar album por ID
POST http://localhost:40000/getAlbumByID HTTP/1.1
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjk5NDQ4NzM0LCJleHAiOjE2OTk0NDkzMzR9.WOT4pv8ejaGYL1osdPPfaJ4NbimwgNlrB56yWprZsj0

{    
    "albumid": 1
}

### teste de inserção de album
POST http://localhost:40000/insertAlbum HTTP/1.1
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjk5NDQ4NzM0LCJleHAiOjE2OTk0NDkzMzR9.WOT4pv8ejaGYL1osdPPfaJ4NbimwgNlrB56yWprZsj0

{    
    "albumid": 2,
    "numero_album": "003",
    "nome_album": "Som de Chuva",
    "data_publicacao": "1999-12-12",
    "valor": 1000.00,
    "distribuidoraid": 2,
    "removido": false
}

### teste de atualização de album
POST http://localhost:40000/updateAlbum HTTP/1.1
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjk5NDQ4NzM0LCJleHAiOjE2OTk0NDkzMzR9.WOT4pv8ejaGYL1osdPPfaJ4NbimwgNlrB56yWprZsj0

{    
    "albumid": 3,
    "numero_album": "004",
    "nome_album": "Musicas para corrida",
    "data_publicacao": "2014-08-07",
    "valor": 9050.80,
    "distribuidoraid": 1,
    "removido": false
}

### teste de atualização de album
POST http://localhost:40000/DeleteAlbum HTTP/1.1
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjk5NDQ4NzM0LCJleHAiOjE2OTk0NDkzMzR9.WOT4pv8ejaGYL1osdPPfaJ4NbimwgNlrB56yWprZsj0

{    
    "albumid": 55  
}
