### teste de buscar todos os distribuidora
GET http://localhost:40000/GetAllDistribuidora HTTP/1.1
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzQ3ODI5NzksInVzZXJuYW1lIjoicXdlIn0.SlYYCm8J6wlpb3i1jJcSvhSz6VjwKvzPOxza8P6-hzo

{    
    
}

### teste de buscar distribuidora por ID
POST http://localhost:40000/GetDistribuidoraByID HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTY5ODE1MzE4MywiZXhwIjoxNjk4MTUzNzgzfQ.O3F43FZOtxdh_YuGrj02a7Dc06P4qqipLN0kbyZtBrw

{    
    "distribuidoraid": 1
}

### teste de inserção de distribuidora
POST http://localhost:40000/InsertDistribuidora HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTY5ODE1MzE4MywiZXhwIjoxNjk4MTUzNzgzfQ.O3F43FZOtxdh_YuGrj02a7Dc06P4qqipLN0kbyZtBrw

{    
    "distribuidoraid": 1,
    "numero_distribuidora": 111,
    "nome_distribuidora": "Proximo ao Porecatu",
    "sede_distribuidora": "Santander",
    "fundacao": "01/01/2001",
    "taxa_vendas": 2.0,
    "ativo": true,
    "removido": false    
}

### teste de atualização de distribuidora
POST http://localhost:40000/UpdateDistribuidora HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTY5ODE1MzE4MywiZXhwIjoxNjk4MTUzNzgzfQ.O3F43FZOtxdh_YuGrj02a7Dc06P4qqipLN0kbyZtBrw

{    
    "distribuidoraid": 1,
    "numero_distribuidora": 223,
    "nome_distribuidora": "Proximo ao Porecatu ALTERADO",
    "sede_distribuidora": "Santander ALTERADO",
    "fundacao": "02/02/2002",
    "taxa_vendas": 2.0,
    "ativo": true,
    "removido": false   
}

### teste de remover a distribuidora
POST http://localhost:40000/DeleteDistribuidora HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTY5ODE1MzE4MywiZXhwIjoxNjk4MTUzNzgzfQ.O3F43FZOtxdh_YuGrj02a7Dc06P4qqipLN0kbyZtBrw

{    
    "distribuidoraid": 1 
}
